# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a39034efc24ff5d10ff437d2eb79da357308316d0bac33966b5d0b1434a4ba3d4382afb0957a6ef3757100e3780b45e0963153232c73b93acf2f3059d1893638

test:
  secret_key_base: dfaee1707fc4274b186ab491d792afbccff482078e34de392681a621487fa2eb90acc18bdef8447a5eb584144ba64bd3ea527750e54f1e4de3d1447afea8d06d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
